title: Amr El-Azizi
logo: /assets/headshot.png
description: I'm a Columbia University graduate with a Masters' degree in Mechanical Engineering with a focus on Robotics. I've done research in a variety of fields from Tactile and Force Sensing, Neural Networks for processing real world data, and Simulation Environments for Robotics. Previously, I completed an Undergraduate Degree in Electrical and Computer Engineering at UT Austin where I served as President of the Robotics Club. I have multiple years of research and work experience across a mix of software and hardware that I hope to continue to develop my skills in.
show_downloads: false
theme: jekyll-theme-minimal
